name: Draft Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
          token: ${{ secrets.GITHUB_TOKEN }}
